<?php

namespace Database\Seeders;

use App\Models\Vehicle;
use Illuminate\Database\Seeder;

class VehiclesSeeder extends Seeder
{
    public function run(): void
    {
        $vehicles = [
            [
                'name'       => 'BZ4X',
                'slug'       => 'bz4x',
                'full_name'  => 'BZ4X Limited 4x2',
                'subtitle'   => 'Más que un eléctrico, un eléctrico Toyota.',
                'type'       => 'SUV',
                'fuel'       => 'Eléctrico',
                'hero_image' => null,
                'gallery'    => [],
                'highlights' => [
                    ['title' => 'Motor eléctrico', 'value' => '150 kW (201 HP)'],
                    ['title' => 'Autonomía', 'value' => '516 km (WLTP)'],
                    ['title' => 'Tracción', 'value' => 'Delantera 4x2'],
                    ['title' => '0-100 km/h', 'value' => '7.5 seg'],
                ],
                'is_visible' => true,
                'order'      => 1,
                'versions'   => [
                    [
                        'name'     => 'BZ4X Limited 4x2',
                        'price'    => '$ 39.990.000',
                        'electric' => true,
                        'bonus'    => 'Incluye Bono de $3.000.000 con financiamiento',
                        'pricing'  => [
                            ['label' => 'Crédito inteligente',            'value' => '$39.990.990'],
                            ['label' => 'Crédito convencional',           'value' => '$40.990.990'],
                            ['label' => 'Crédito todo medio de pago',     'value' => '$39.990.990'],
                            ['label' => 'Precio de lista',                'value' => '$39.990.990'],
                        ],
                        'motor' => [
                            ['label' => 'Transmisión',    'value' => 'Automática'],
                            ['label' => 'Combustible',    'value' => 'Eléctrico'],
                            ['label' => 'Cilindrada',     'value' => '1'],
                            ['label' => 'Potencia (HP)',  'value' => '221'],
                            ['label' => 'Tracción',       'value' => '4x2'],
                            ['label' => 'Puertas',        'value' => '5'],
                            ['label' => 'Asientos',       'value' => '5'],
                        ],
                        'interior' => [
                            ['label' => 'A/C',                        'value' => 'Sí'],
                            ['label' => 'Climatizador',               'value' => 'General'],
                            ['label' => 'Alzavidrios eléctricos',     'value' => 'Sí'],
                            ['label' => 'Retrovisor',                 'value' => 'Electrocromático'],
                            ['label' => 'Radio',                      'value' => 'Pantalla Touch'],
                            ['label' => 'Pantalla radio (")',         'value' => '14'],
                            ['label' => 'Parlantes',                  'value' => '6'],
                            ['label' => 'Apple CarPlay',              'value' => 'Sí'],
                            ['label' => 'Android Auto',               'value' => 'Sí'],
                            ['label' => 'Bluetooth',                  'value' => 'Sí'],
                            ['label' => 'Mando al volante',           'value' => 'Sí'],
                            ['label' => 'Velocidad crucero',          'value' => 'Sí'],
                            ['label' => 'Smart key',                  'value' => 'Sí'],
                            ['label' => 'Botón encendido',            'value' => '-'],
                            ['label' => 'Tapiz',                      'value' => 'Eco-cuero'],
                            ['label' => 'Asientos eléctricos',        'value' => 'Sí'],
                            ['label' => 'Asientos calefaccionados',   'value' => 'Delantero + trasero'],
                            ['label' => 'Volante tapiz cuero',        'value' => 'Sí'],
                        ],
                        'exterior' => [
                            ['label' => 'Llantas',            'value' => 'Aleación'],
                            ['label' => 'Medidas llantas (")', 'value' => '18'],
                            ['label' => 'Focos Led',           'value' => 'Sí'],
                            ['label' => 'Focos inteligentes',  'value' => '-'],
                            ['label' => 'Neblineros',          'value' => 'Sí'],
                            ['label' => 'Espejos eléctricos',  'value' => 'Sí'],
                            ['label' => 'Portalón',            'value' => 'Trasero eléctrico'],
                        ],
                        'seguridad' => [
                            ['label' => 'Airbag',                           'value' => '8'],
                            ['label' => 'Control estabilidad',              'value' => 'Sí'],
                            ['label' => 'Control de tracción',              'value' => 'Sí'],
                            ['label' => 'ABS',                              'value' => 'Sí'],
                            ['label' => 'EBD',                              'value' => 'Sí'],
                            ['label' => 'Hill assist',                      'value' => 'Sí'],
                            ['label' => 'Frenos delanteros',                'value' => 'Disco'],
                            ['label' => 'Frenos traseros',                  'value' => 'Disco'],
                            ['label' => 'Freno de mano eléctrico',          'value' => 'Sí'],
                            ['label' => 'Freno automático de emergencia',   'value' => 'Sí'],
                            ['label' => 'Sensor de presión de neumáticos',  'value' => 'Sí'],
                            ['label' => 'Detector de punto ciego',          'value' => 'Sí'],
                            ['label' => 'Alerta de cambio de carril',       'value' => 'Sí'],
                            ['label' => 'Cámara de retroceso',              'value' => 'Sí'],
                            ['label' => 'ISOFIX',                           'value' => 'Sí'],
                            ['label' => 'Rueda repuesto',                   'value' => 'Emergencia'],
                        ],
                        'rendimiento' => [
                            ['label' => 'Autonomía',   'value' => '516 km'],
                            ['label' => 'Batería',     'value' => '71.4 kWh'],
                            ['label' => 'Carga AC',    'value' => '11 kW'],
                            ['label' => 'Carga DC',    'value' => '150 kW'],
                            ['label' => '0-100',       'value' => '7.5 seg'],
                            ['label' => 'Vel. máx.',   'value' => '160 km/h'],
                        ],
                    ],
                    [
                        'name'     => 'BZ4X AWD',
                        'price'    => '$ 44.990.000',
                        'electric' => true,
                        'bonus'    => 'Incluye Bono de $3.000.000 con financiamiento',
                        'pricing'  => [
                            ['label' => 'Crédito inteligente',        'value' => '$44.990.990'],
                            ['label' => 'Crédito convencional',       'value' => '$45.990.990'],
                            ['label' => 'Crédito todo medio de pago', 'value' => '$44.990.990'],
                            ['label' => 'Precio de lista',            'value' => '$44.990.990'],
                        ],
                        'motor' => [
                            ['label' => 'Transmisión',    'value' => 'Automática'],
                            ['label' => 'Combustible',    'value' => 'Eléctrico'],
                            ['label' => 'Cilindrada',     'value' => '2'],
                            ['label' => 'Potencia (HP)',  'value' => '218'],
                            ['label' => 'Tracción',       'value' => '4x4'],
                            ['label' => 'Puertas',        'value' => '5'],
                            ['label' => 'Asientos',       'value' => '5'],
                        ],
                        'interior' => [
                            ['label' => 'A/C',                        'value' => 'Sí'],
                            ['label' => 'Climatizador',               'value' => 'Dual'],
                            ['label' => 'Alzavidrios eléctricos',     'value' => 'Sí'],
                            ['label' => 'Retrovisor',                 'value' => 'Electrocromático'],
                            ['label' => 'Radio',                      'value' => 'Pantalla Touch'],
                            ['label' => 'Pantalla radio (")',         'value' => '14'],
                            ['label' => 'Parlantes',                  'value' => '8'],
                            ['label' => 'Apple CarPlay',              'value' => 'Sí'],
                            ['label' => 'Android Auto',               'value' => 'Sí'],
                            ['label' => 'Bluetooth',                  'value' => 'Sí'],
                            ['label' => 'Mando al volante',           'value' => 'Sí'],
                            ['label' => 'Velocidad crucero',          'value' => 'Adaptativo'],
                            ['label' => 'Smart key',                  'value' => 'Sí'],
                            ['label' => 'Botón encendido',            'value' => 'Sí'],
                            ['label' => 'Tapiz',                      'value' => 'Cuero'],
                            ['label' => 'Asientos eléctricos',        'value' => 'Sí'],
                            ['label' => 'Asientos calefaccionados',   'value' => 'Delantero + trasero'],
                            ['label' => 'Volante tapiz cuero',        'value' => 'Sí'],
                        ],
                        'exterior' => [
                            ['label' => 'Llantas',             'value' => 'Aleación'],
                            ['label' => 'Medidas llantas (")',  'value' => '20'],
                            ['label' => 'Focos Led',            'value' => 'Sí'],
                            ['label' => 'Focos inteligentes',   'value' => 'Sí'],
                            ['label' => 'Neblineros',           'value' => 'Sí'],
                            ['label' => 'Espejos eléctricos',   'value' => 'Sí'],
                            ['label' => 'Portalón',             'value' => 'Manos libres'],
                        ],
                        'seguridad' => [
                            ['label' => 'Airbag',                           'value' => '9'],
                            ['label' => 'Control estabilidad',              'value' => 'Sí'],
                            ['label' => 'Control de tracción',              'value' => 'Sí'],
                            ['label' => 'ABS',                              'value' => 'Sí'],
                            ['label' => 'EBD',                              'value' => 'Sí'],
                            ['label' => 'Hill assist',                      'value' => 'Sí'],
                            ['label' => 'Frenos delanteros',                'value' => 'Disco'],
                            ['label' => 'Frenos traseros',                  'value' => 'Disco'],
                            ['label' => 'Freno de mano eléctrico',          'value' => 'Sí'],
                            ['label' => 'Freno automático de emergencia',   'value' => 'Sí'],
                            ['label' => 'Sensor de presión de neumáticos',  'value' => 'Sí'],
                            ['label' => 'Detector de punto ciego',          'value' => 'Sí'],
                            ['label' => 'Alerta de cambio de carril',       'value' => 'Sí'],
                            ['label' => 'Cámara de retroceso',              'value' => '360°'],
                            ['label' => 'ISOFIX',                           'value' => 'Sí'],
                            ['label' => 'Rueda repuesto',                   'value' => 'Emergencia'],
                        ],
                        'rendimiento' => [
                            ['label' => 'Autonomía',   'value' => '470 km'],
                            ['label' => 'Batería',     'value' => '71.4 kWh'],
                            ['label' => 'Carga AC',    'value' => '11 kW'],
                            ['label' => 'Carga DC',    'value' => '150 kW'],
                            ['label' => '0-100',       'value' => '6.5 seg'],
                            ['label' => 'Vel. máx.',   'value' => '160 km/h'],
                        ],
                    ],
                ],
            ],
            [
                'name'       => 'Hilux',
                'slug'       => 'hilux',
                'full_name'  => 'Hilux SR5 4x4',
                'subtitle'   => 'La pickup más vendida de Chile.',
                'type'       => 'Pickup',
                'fuel'       => 'Diésel',
                'hero_image' => null,
                'gallery'    => [],
                'highlights' => [
                    ['title' => 'Motor',      'value' => '2.8L Turbodiesel'],
                    ['title' => 'Potencia',   'value' => '204 HP'],
                    ['title' => 'Tracción',   'value' => '4x4'],
                    ['title' => 'Carga útil', 'value' => '1.000 kg'],
                ],
                'is_visible' => true,
                'order'      => 2,
                'versions'   => [
                    [
                        'name'     => 'Hilux SR5 4x4',
                        'price'    => '$ 29.990.000',
                        'electric' => false,
                        'bonus'    => '',
                        'pricing'  => [
                            ['label' => 'Crédito inteligente',        'value' => '$29.990.990'],
                            ['label' => 'Crédito convencional',       'value' => '$30.990.990'],
                            ['label' => 'Precio de lista',            'value' => '$29.990.990'],
                        ],
                        'motor' => [
                            ['label' => 'Transmisión',    'value' => 'Automática 6V'],
                            ['label' => 'Combustible',    'value' => 'Diésel'],
                            ['label' => 'Cilindrada',     'value' => '2.755 cc'],
                            ['label' => 'Potencia (HP)',  'value' => '204'],
                            ['label' => 'Tracción',       'value' => '4x4'],
                            ['label' => 'Puertas',        'value' => '4'],
                            ['label' => 'Asientos',       'value' => '5'],
                        ],
                        'interior' => [
                            ['label' => 'A/C',                     'value' => 'Sí'],
                            ['label' => 'Climatizador',            'value' => 'Dual'],
                            ['label' => 'Alzavidrios eléctricos',  'value' => 'Sí'],
                            ['label' => 'Retrovisor',              'value' => 'Electrocromático'],
                            ['label' => 'Radio',                   'value' => 'Pantalla Touch'],
                            ['label' => 'Pantalla radio (")',      'value' => '9'],
                            ['label' => 'Parlantes',               'value' => '6'],
                            ['label' => 'Apple CarPlay',           'value' => 'Sí'],
                            ['label' => 'Android Auto',            'value' => 'Sí'],
                            ['label' => 'Bluetooth',               'value' => 'Sí'],
                            ['label' => 'Mando al volante',        'value' => 'Sí'],
                            ['label' => 'Velocidad crucero',       'value' => 'Sí'],
                            ['label' => 'Smart key',               'value' => 'Sí'],
                            ['label' => 'Botón encendido',         'value' => 'Sí'],
                            ['label' => 'Tapiz',                   'value' => 'Cuero'],
                            ['label' => 'Asientos eléctricos',     'value' => 'Sí'],
                            ['label' => 'Asientos calefaccionados','value' => 'Delantero'],
                            ['label' => 'Volante tapiz cuero',     'value' => 'Sí'],
                        ],
                        'exterior' => [
                            ['label' => 'Llantas',             'value' => 'Aleación'],
                            ['label' => 'Medidas llantas (")',  'value' => '17'],
                            ['label' => 'Focos Led',            'value' => 'Sí'],
                            ['label' => 'Focos inteligentes',   'value' => '-'],
                            ['label' => 'Neblineros',           'value' => 'Sí'],
                            ['label' => 'Espejos eléctricos',   'value' => 'Sí'],
                            ['label' => 'Portalón',             'value' => 'Manual'],
                        ],
                        'seguridad' => [
                            ['label' => 'Airbag',                          'value' => '7'],
                            ['label' => 'Control estabilidad',             'value' => 'Sí'],
                            ['label' => 'Control de tracción',             'value' => 'Sí'],
                            ['label' => 'ABS',                             'value' => 'Sí'],
                            ['label' => 'EBD',                             'value' => 'Sí'],
                            ['label' => 'Hill assist',                     'value' => 'Sí'],
                            ['label' => 'Frenos delanteros',               'value' => 'Disco'],
                            ['label' => 'Frenos traseros',                 'value' => 'Disco'],
                            ['label' => 'Freno de mano eléctrico',         'value' => 'Sí'],
                            ['label' => 'Freno automático de emergencia',  'value' => 'Sí'],
                            ['label' => 'Sensor de presión de neumáticos', 'value' => 'Sí'],
                            ['label' => 'Detector de punto ciego',         'value' => 'Sí'],
                            ['label' => 'Alerta de cambio de carril',      'value' => 'Sí'],
                            ['label' => 'Cámara de retroceso',             'value' => 'Sí'],
                            ['label' => 'ISOFIX',                          'value' => 'Sí'],
                            ['label' => 'Rueda repuesto',                  'value' => 'Completa'],
                        ],
                        'rendimiento' => [
                            ['label' => 'Consumo ciudad',    'value' => '9.5 L/100km'],
                            ['label' => 'Consumo carretera', 'value' => '7.2 L/100km'],
                            ['label' => 'Torque',            'value' => '500 Nm'],
                            ['label' => '0-100',             'value' => '9.8 seg'],
                            ['label' => 'Vel. máx.',         'value' => '175 km/h'],
                        ],
                    ],
                ],
            ],
        ];

        foreach ($vehicles as $v) {
            Vehicle::updateOrCreate(['slug' => $v['slug']], $v);
        }
    }
}
